require_relative "traders/table_base"
require_relative "traders/scotiabank"
require_relative "traders/ncb"
require_relative "traders/fx_trader"
require_relative "traders/jnbs"
require_relative "traders/jmmb"
