# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5492dc42230ad90b9b49ff415ed33e872796d87405bc3147843e7f5162e0fe5ae4c9b93fe9fee1ca44bd09867a18f08eb9a26b2d7a8ae79581695a426401f1b

test:
  secret_key_base: 7c2a8e93de639062f6b179a0d6fca8fc927219e3909a4979319af6adfe014b18d3eb1467cb2031280d7f775e43ab347a34c568639695910ed3f137aeb1eed0b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
